#!/usr/bin/python
import argparse

parser = argparse.ArgumentParser(description='Read a file in reverse')
parser.add_argument('filename', help='the file to read')
parser.add_argument('--limit', type=int, help='the number of lines to read')
parser.add_argument('--version', '-v', action='version', version='%(prog)s 2.0')

args = parser.parse_args()

try:
    f = open(args.filename, 'r')
    limit = args.limit
except:
    print("Error reading file")
else:
    with f:
        lines = f.readlines()
        lines.reverse()

        if limit:
            lines = lines[:limit]

        for line in lines:
            print(line.strip()[::-1])
finally:
    print("\nWe've finished\n")
